### PR TITLE
Add option to define a package that will be imported

### LINKED ISSUE #48: Source package not imported if interfaces placed in different package
If one generates an interface into a different package than the source package, e.g.:

```
ifacemaker -f ../bindings.go -s MyStruct -o i_mystruct.go -p interfaces -i IMyStruct
```

Then the generated code may be invalid if any of the method signatures contain custom types defined in the source package, e.g.: the generated code in the `interfaces` package references a custom type defined in the source package as `MyType` instead of importing from the source package and refering to it as `bindings.MyType`

### PR DESCRIPTION
**Pull request by Skarlso**
Closes #48 

Usage:

```
AWS_SDK_DIR=/Users/skarlso/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/sts@v1.16.3
./ifacemaker -f '/Users/skarlso/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/sts@v1.16.3/*.go' -s Client -i STS -p awsapi -y 'STS provides an interface to the AWS STS service.' -c 'Code generated by ifacemaker; DO NOT EDIT.' -m github.com/aws/aws-sdk-go-v2/service/sts
```

Produces:

```go
// Code generated by ifacemaker; DO NOT EDIT.

package awsapi

import (
	"context"

	. "github.com/aws/aws-sdk-go-v2/service/sts"
)

// STS provides an interface to the AWS STS service.
type STS interface {
        // ... lots of comments
	AssumeRole(ctx context.Context, params *AssumeRoleInput, optFns ...func(*Options)) (*AssumeRoleOutput, error)
```

Note, that now `*AssumeRoleInput` works as expected. The import `	. "github.com/aws/aws-sdk-go-v2/service/sts"` has been correctly added to the list of imports.

### CODE REVIEW

**Comment by Skarlso** [comment]
Running unit tests locally:

```go
go test ./...
ok      github.com/vburenin/ifacemaker  0.490s
ok      github.com/vburenin/ifacemaker/maker    0.300s
➜  ifacemaker git:(fix_source_package_vs_target_package)
```

This change will allow us to drop using an extra script here: https://github.com/weaveworks/eksctl/issues/4994

If this is merged and released we can ditch our hack around missing imports.

We would greatly appreciate that. :) thanks!

**Comment by vburenin** [comment]
whatever... if it helps %-)

**Comment by Skarlso** [comment]
Best comment ever. 😂 Thank you, it does. 😊

**Comment by vburenin** [comment]
I actually not exactly agree with this. Dot imports are really bad, I simply have no time and capability to build and test this, so I bet on the community to do the right thing. Make sure you don't shoot yourself into the foot.

**Comment by vburenin** [comment]
Is this one actually better? https://github.com/rjeczalik/interfaces

**Comment by Skarlso** [comment]
@vburenin Why are dot imports bad? They are a language feature. And you have to define them explicitly, so there shouldn't be too much a problem with them. If you don't set this, you won't get into trouble. Although what trouble do you envision?

If it's the same package you import, you should be doing okay. :)

**Comment by vburenin** [comment]
Imports into the package space are considered bad practices in any
programming language I am aware of except C where it is just life. There is
a chance of the name collisions and it makes harder to distinguish between
local package definitions and the package level. Having a language feature
doesn’t mean it is a good thing.

**Comment by Skarlso** [comment]
This argument doesn't hold since you already are in the package you are importing into the target package. You know the target package. Of course if the target package has the same naming as the source package that will be a problem. But in that case don't do this and you should be fine. That said, I understand what you are saying that's why it's an option explicitly defined by the user. The alternative would be to give an optional alias and prepend all package local variables.

**Comment by vburenin** [comment]
I have no incentive to convince anybody. Do it the way you think it is best
for you.

**Pull request merged**
